id: P000752
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:40:57.684188
source_metadata:
  id: bdr:W3CN4798
  title: རྟགས་རིགས་ཕྱོགས་བསྡུས་རིགས་ལམ་སྒོ་བརྒྱ་འབྱེད་པའི་ལྡེ་མིག
  author: ''
  volumes:
    0027c1f398fa4cea82d17071009b0785:
      image_group_id: I3CN4800
      title: ''
      volume_number: 1
      total_pages: 424
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
